#pragma checksum "D:\Project\C#\NegativeScreen\NegativeScreen\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D1BEDF3714602A5A3A3863AC062E0E868E81A05BA71ADF09EE4ACAB01E55EE7E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegativeScreen
{
    partial class App : global::Windows.UI.Xaml.Application
    {
    }
}

